name       : paperwork-backend
version    : 2.0.3
release    : 13
source     :
    - https://pypi.io/packages/source/o/paperwork-backend/paperwork-backend-2.0.3.tar.gz : 3f0bd32dbbad43464692ba5f1a457478e16c16f8881c58a89632604a4c5f1afa
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : Backend part of Paperwork (Python API, no UI)
description: |
    Paperwork is a GUI to make papers searchable. This is the backend part of Paperwork.
builddeps  :
    - libinsane
    - libpillowfight
    - openpaperwork-core
    - openpaperwork-gtk
    - poppler
    - python-gobject
    - python-levenshtein
    - python-psutil
    - python-pycountry
    - python-pyocr
    - python-simplebayes
    - python-whoosh
    - python3-cairo
rundeps:
    - libinsane
    - libpillowfight
    - openpaperwork-core
    - openpaperwork-gtk
    - poppler
    - python-gobject
    - python-levenshtein
    - python-pycountry
    - python-pyocr
    - python-simplebayes
    - python-whoosh
    - python3-cairo
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
