name       : paperwork-backend
version    : 1.3.1
release    : 7
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/1.3.1/paperwork-1.3.1.tar.gz : 70a3b9faf8d5edcd54fa1dd8cb4f517d319a18efe9898fce3b9cb43b2564885a
license    : GPL-3.0-or-later
component  : programming.python
summary    : Backend part of Paperwork (Python API, no UI)
description: |
    Paperwork is a GUI to make papers searchable. This is the backend part of Paperwork.
builddeps  :
    - git
rundeps    :
    - libpillowfight
    - pyenchant
    - python-levenshtein
    - python-natsort
    - python-pycountry
    - python-simplebayes
    - python-termcolor
    - python-whoosh
build      : |
    %make
install    : |
    pushd paperwork-backend
      %python3_install
    popd
