name       : paperwork-backend
version    : 2.1.0
release    : 15
source     :
    - https://pypi.io/packages/source/p/paperwork-backend/paperwork-backend-2.1.0.tar.gz : 5791b352cd823bde5b6825792398cfe2e5f19664217b904588a7a29349e44c9a
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : Backend part of Paperwork (Python API, no UI)
description: |
    Paperwork is a GUI to make papers searchable. This is the backend part of Paperwork.
builddeps  :
    - libinsane
    - libpillowfight
    - openpaperwork-core
    - openpaperwork-gtk
    - poppler
    - python-gobject
    - python-levenshtein
    - python-pycountry
    - python-pyocr
    - python-simplebayes
    - python-whoosh
    - scikit-learn
rundeps    :
    - libinsane
    - libpillowfight
    - openpaperwork-core
    - openpaperwork-gtk
    - poppler
    - python-gobject
    - python-levenshtein
    - python-pycountry
    - python-pyocr
    - python-simplebayes
    - python-whoosh
    - scikit-learn
build      : |
    %python3_setup
install    : |
    %python3_install
