name       : paperwork-backend
version    : 1.3.0
release    : 5
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/paperwork/-/archive/1.3.0/paperwork-1.3.0.tar.gz : 4070ffd21197a7e20ade035fb63e5448ea7ca1eb9a27d32098ec49108aaad23a
license    : GPL-3.0-or-later
component  : programming.python
summary    : Backend part of Paperwork (Python API, no UI)
description: |
    Paperwork is a GUI to make papers searchable. This is the backend part of Paperwork.
builddeps  :
    - git
rundeps    :
    - libpillowfight
    - pyenchant
    - python-levenshtein
    - python-pycountry
    - python-simplebayes
    - python-termcolor
    - python-whoosh
build      : |
    %make
install    : |
    pushd paperwork-backend
      %python3_install
    popd
