name       : paperwork-backend
version    : 1.1.2
release    : 3
source     :
    - https://github.com/openpaperwork/paperwork-backend/archive/1.1.2.tar.gz : 19b15ed995b06bd9d9a61c82389983feaaaa6d5dffe41b88e87bbe3a5e297dd8
license    : GPL-3.0
component  : programming.python
summary    : Backend part of Paperwork (Python API, no UI)
description: |
    Paperwork is a GUI to make papers searchable. This is the backend part of Paperwork.
rundeps    :
    - libpillowfight
    - pyenchant
    - python-levenshtein
    - python-pycountry
    - python-simplebayes
    - python-termcolor
    - python-whoosh
build      : |
    %python3_setup
install    : |
    %python3_install
